application: pi-schooldb-dev
version: 1--0-18
api_version: 1
runtime: python

#Check DEBUG in settings.py

handlers:

- url: /static_pages
  static_dir: static_pages
 
- url: /js
  static_dir: js
  
- url: /css
  static_dir: css
  
- url: /media
  static_dir: media
  expiration: "5d 0h"
  
- url: /upload_data
  static_dir: upload_data
  
- url: /utilrequest
  script: main.py
  login: admin
  secure: always
  
- url: /runtest
  script: main.py
  login: admin
  secure: always
  
- url: /static_tasks/(.*)
  script: /static_tasks/\1.py
  login: admin
  secure: always
 
- url: /task
  script: main.py
  login: admin
  secure: always

- url: /.*
  script: main.py
  login: required


builtins:
- django_wsgi: on
- remote_api: on
- appstats: on
#- datastore_admin: on

#inbound_services:
#- warmup
