application: pi-schooldb-dev
version: 1--0-11
runtime: python
api_version: 1

handlers:

- url: /static_pages
  static_dir: static_pages
 
- url: /js
  static_dir: js
  
- url: /css
  static_dir: css
  
- url: /media
  static_dir: media
  
- url: /upload_data
  static_dir: upload_data
  
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /utilrequest
  script: main.py
  login: admin
  
- url: /runtest
  script: main.py
  login: admin
  
- url: /static_tasks/(.*)
  script: /static_tasks/\1.py
  login: admin
  secure: always
 
- url: /task
  script: /main.py
  login: admin
  secure: always

- url: /.*
  script: main.py
  login: required
  secure: always

builtins:
- datastore_admin: on
- appstats: on
