application: pi-schooldb-practice
version: 1--0-13
runtime: python
api_version: 1

handlers:

- url: /static_pages

  static_dir: static_pages
 
- url: /js
  static_dir: js
  
- url: /css
  static_dir: css
  
- url: /media
  static_dir: media
  
- url: /upload_data
  static_dir: upload_data
  
- url: /utilrequest
  script: main.py
  login: admin
  
- url: /runtest
  script: main.py
  login: admin
  
- url: /static_tasks/(.*)
  script: /static_tasks/\1.py
  login: admin
  secure: always
 
- url: /task
  script: /main.py
  login: admin

- url: /.*
  script: main.py
  login: required

builtins:
- remote_api: on
- datastore_admin: on
- appstats: on
